version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seguridad2023
      POSTGRES_DB: cursoSpring
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: BACK/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db



volumes:
  postgres_data:


