version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seguridad2023
      POSTGRES_DB: cursoSpring
    ports:
      - 5432:5432