version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cursoSpring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=seguridad2023
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SECURITY.JWT.SECRET=cursoSpring
      - SECURITY.JWT.EXPIRATION=86400000
      - SECURITY.JWT.ISSUER=Main

  db:
    image: 'postgres:13.1-alpine'
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seguridad2023
      POSTGRES_DB: cursoSpring
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
